"""Retained v0.5 flat structured substrate public interfaces."""

from aethersparse.substrate.binary_pack import (
    BinaryPackError,
    FlatBinaryPackReader,
    shard_for_key,
    write_flat_binary_pack,
)
from aethersparse.substrate.builder import (
    StructuredSubstrateBuilder,
    SubstrateBuildError,
    normalize_surface,
    sha256_text,
    tokenize,
    validate_source_bindings,
)
from aethersparse.substrate.extraction import extract_claim_seeds, iter_claim_seeds
from aethersparse.substrate.models import (
    AliasKind,
    AliasRecord,
    AnchorRecord,
    BinaryPackArtifact,
    BinaryPackManifest,
    BinaryQueryRead,
    BinarySection,
    ChunkRecord,
    ClaimAttribute,
    ClaimKind,
    ClaimSeed,
    DocumentRecord,
    EntityRecord,
    ExplicitAliasSeed,
    FlatIndexes,
    FlatStructuredPack,
    FusionFeatures,
    HeadingRecord,
    ObjectKind,
    PackReadTrace,
    Posting,
    RedirectRecord,
    RetrievalRequest,
    RetrievalResult,
    RetrievedEvidence,
    SourceBinding,
    SourcePage,
    StructuredClaim,
    SubstrateMetadata,
)
from aethersparse.substrate.retrieval import FlatHybridRetriever
from aethersparse.substrate.sqlite_bridge import (
    build_selected_substrate_from_sqlite,
    iter_source_pages_from_sqlite,
    substrate_metadata_from_sqlite,
)

__all__ = [
    "AliasKind",
    "AliasRecord",
    "AnchorRecord",
    "BinaryPackArtifact",
    "BinaryPackError",
    "BinaryPackManifest",
    "BinaryQueryRead",
    "BinarySection",
    "ChunkRecord",
    "ClaimAttribute",
    "ClaimKind",
    "ClaimSeed",
    "DocumentRecord",
    "EntityRecord",
    "ExplicitAliasSeed",
    "FlatBinaryPackReader",
    "FlatHybridRetriever",
    "FlatIndexes",
    "FlatStructuredPack",
    "FusionFeatures",
    "HeadingRecord",
    "ObjectKind",
    "PackReadTrace",
    "Posting",
    "RedirectRecord",
    "RetrievalRequest",
    "RetrievalResult",
    "RetrievedEvidence",
    "SourceBinding",
    "SourcePage",
    "StructuredClaim",
    "StructuredSubstrateBuilder",
    "SubstrateBuildError",
    "SubstrateMetadata",
    "build_selected_substrate_from_sqlite",
    "extract_claim_seeds",
    "iter_claim_seeds",
    "iter_source_pages_from_sqlite",
    "normalize_surface",
    "sha256_text",
    "shard_for_key",
    "substrate_metadata_from_sqlite",
    "tokenize",
    "validate_source_bindings",
    "write_flat_binary_pack",
]
