"""Versioned compilation plus bounded exact and approximate address channels."""

from aethersparse.addressing.benchmark_v2 import (
    BENCHMARK_CAPTURE_SCHEMA_VERSION,
    compile_benchmark_capture,
)
from aethersparse.addressing.bundle_v2 import (
    AddressBundleIdentity,
    CanonicalAddressRegistry,
    compile_verified_exact_address_index,
    iter_exact_address_evidence,
    iter_surface_statistics_view,
    load_canonical_registry,
    verify_address_bundle,
)
from aethersparse.addressing.compiler_v2 import (
    ADDRESS_EXPORT_SCHEMA_VERSION,
    AddressArtifactError,
    AddressExportManifest,
    compile_address_pack,
    verify_address_export,
)
from aethersparse.addressing.contracts_v2 import (
    AddressChannelV2,
    fusion_channel_name,
    stable_record_id,
    validate_record_contract,
)
from aethersparse.addressing.exact import (
    AddressChannel,
    AddressEvidence,
    AddressIndexArtifact,
    AddressIndexError,
    AddressPosting,
    ExactAddressIndex,
    ExactAddressLookup,
    compile_exact_address_index,
    normalize_surface,
)
from aethersparse.addressing.factory_export_v2 import export_v11_benchmark_capture
from aethersparse.addressing.semantic_ann import (
    CorpusSourceSplit,
    HyperlinkSupervision,
    ProductQuantizer,
    SemanticSupervisionBundle,
    StaticSubwordEncoder,
    TrainingReadiness,
    binary_code,
    build_binary_ivf,
    calibration_supervision,
    fit_product_quantizer,
    fit_supervision,
    holdout_qualification,
    load_compiler_supervision,
    progressive_ivf_search,
    semantic_index_manifest_document,
    semantic_manifest_contract,
    semantic_supervision_manifest_document,
    training_readiness,
    verify_semantic_supervision_manifest,
    write_semantic_index_manifest,
    write_semantic_supervision_manifest,
)

__all__ = [
    "ADDRESS_EXPORT_SCHEMA_VERSION",
    "BENCHMARK_CAPTURE_SCHEMA_VERSION",
    "AddressArtifactError",
    "AddressBundleIdentity",
    "AddressChannel",
    "AddressChannelV2",
    "AddressEvidence",
    "AddressExportManifest",
    "AddressIndexArtifact",
    "AddressIndexError",
    "AddressPosting",
    "CanonicalAddressRegistry",
    "CorpusSourceSplit",
    "ExactAddressIndex",
    "ExactAddressLookup",
    "HyperlinkSupervision",
    "ProductQuantizer",
    "SemanticSupervisionBundle",
    "StaticSubwordEncoder",
    "TrainingReadiness",
    "binary_code",
    "build_binary_ivf",
    "calibration_supervision",
    "compile_address_pack",
    "compile_benchmark_capture",
    "compile_exact_address_index",
    "compile_verified_exact_address_index",
    "export_v11_benchmark_capture",
    "fit_product_quantizer",
    "fit_supervision",
    "fusion_channel_name",
    "holdout_qualification",
    "iter_exact_address_evidence",
    "iter_surface_statistics_view",
    "load_canonical_registry",
    "load_compiler_supervision",
    "normalize_surface",
    "progressive_ivf_search",
    "semantic_index_manifest_document",
    "semantic_manifest_contract",
    "semantic_supervision_manifest_document",
    "stable_record_id",
    "training_readiness",
    "validate_record_contract",
    "verify_address_bundle",
    "verify_address_export",
    "verify_semantic_supervision_manifest",
    "write_semantic_index_manifest",
    "write_semantic_supervision_manifest",
]
