"""Independent candidate authoring for the sealed Gate 0 query review queue."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from aethersparse.gate0.models import (
    QueryReviewStatus,
    SealedQueryCase,
    SealedQuerySet,
)
from aethersparse.models import Disposition

AUTHOR_IDENTITY = "gate0-query-author-manual-v1"
AUTHORING_PROCESS = (
    "Manually authored challenge cases independent of the deterministic rule "
    "extractor; every case remains pending human review."
)

# id, question, categories, hard, disposition, expected, forbidden,
# intent, entity, relation, evidence source ids
QUERY_SPECS: tuple[tuple[Any, ...], ...] = (
    (
        "q001",
        "When did Apollo 11 launch?",
        ("fact",),
        False,
        "answer",
        ("July 16, 1969",),
        (),
        "TEMPORAL_WHEN",
        "apollo_11",
        "launched_on",
        ("g0_nasa_apollo11_mission_overview",),
    ),
    (
        "q002",
        "On what day did Apollo 11 touch down on the Moon?",
        ("paraphrase",),
        False,
        "answer",
        ("July 20, 1969",),
        (),
        "TEMPORAL_WHEN",
        "apollo_11",
        "landed_on",
        ("g0_nasa_apollo11_mission_overview",),
    ),
    (
        "q003",
        "Name the three Apollo 11 astronauts.",
        ("paraphrase",),
        False,
        "answer",
        ("Armstrong", "Collins", "Aldrin"),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "had_crew",
        ("g0_nasa_apollo11_mission_overview",),
    ),
    (
        "q004",
        "Which lunar module carried the Apollo 11 landing crew?",
        ("fact",),
        False,
        "answer",
        ("Eagle",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "used_vehicle",
        ("g0_nasa_apollo11_mission_card",),
    ),
    (
        "q005",
        "Who spoke the words about one small step?",
        ("quotation", "paraphrase"),
        False,
        "answer",
        ("Neil Armstrong", "one small step"),
        (),
        "QUOTE_WHO_SAID",
        "neil_armstrong",
        "said",
        ("g0_nasa_apollo11_mission_card",),
    ),
    (
        "q006",
        "When did Apollo 11 splash down?",
        ("paraphrase",),
        False,
        "answer",
        ("July 24, 1969",),
        (),
        "TEMPORAL_WHEN",
        "apollo_11",
        "returned_on",
        ("g0_nasa_apollo11_recovery",),
    ),
    (
        "q007",
        "What launch vehicle sent Apollo 11 toward the Moon?",
        ("fact",),
        False,
        "answer",
        ("Saturn V",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "used_vehicle",
        ("g0_nasa_saturn_v",),
    ),
    (
        "q008",
        "What was the lunar module designed to do?",
        ("fact",),
        False,
        "answer",
        ("lunar surface",),
        (),
        "FACT_LOOKUP",
        "lunar_module",
        "purpose",
        ("g0_nasa_lunar_module",),
    ),
    (
        "q009",
        "Was Apollo 4 crewed?",
        ("negation",),
        True,
        "answer",
        ("uncrewed",),
        ("crewed mission",),
        "FACT_LOOKUP",
        "apollo_4",
        "crew_status",
        ("g0_nasa_apollo4",),
    ),
    (
        "q010",
        "What did Apollo 5 test in Earth orbit?",
        ("fact",),
        False,
        "answer",
        ("lunar module",),
        (),
        "FACT_LOOKUP",
        "apollo_5",
        "tested",
        ("g0_nasa_apollo5",),
    ),
    (
        "q011",
        "Which earlier spacecraft did Apollo 12 visit?",
        ("fact",),
        False,
        "answer",
        ("Surveyor III",),
        (),
        "FACT_LOOKUP",
        "apollo_12",
        "visited",
        ("g0_nasa_apollo12",),
    ),
    (
        "q012",
        "What happened during Apollo 12's launch?",
        ("fact",),
        False,
        "answer",
        ("lightning",),
        (),
        "FACT_LOOKUP",
        "apollo_12",
        "launch_event",
        ("g0_nasa_apollo12",),
    ),
    (
        "q013",
        "Did Apollo 13 land on the Moon?",
        ("incorrect_premise", "negation"),
        True,
        "answer",
        ("did not",),
        ("landed on the Moon",),
        "FACT_LOOKUP",
        "apollo_13",
        "landed_on",
        ("g0_nasa_apollo13_review",),
    ),
    (
        "q014",
        "What forced Apollo 13 to abandon its landing?",
        ("fact",),
        True,
        "answer",
        ("oxygen tank",),
        (),
        "FACT_LOOKUP",
        "apollo_13",
        "aborted_because",
        ("g0_nasa_apollo13_review",),
    ),
    (
        "q015",
        "Did the Apollo 13 crew return safely?",
        ("fact",),
        False,
        "answer",
        ("safely",),
        (),
        "FACT_LOOKUP",
        "apollo_13",
        "crew_return",
        ("g0_nasa_apollo13_return",),
    ),
    (
        "q016",
        "Where did Apollo 14 land?",
        ("fact",),
        False,
        "answer",
        ("Fra Mauro",),
        (),
        "FACT_LOOKUP",
        "apollo_14",
        "landed_at",
        ("g0_nasa_apollo14_landing",),
    ),
    (
        "q017",
        "Which mission carried the first lunar roving vehicle?",
        ("paraphrase",),
        False,
        "answer",
        ("Apollo 15",),
        (),
        "FACT_LOOKUP",
        "lunar_roving_vehicle",
        "first_used_by",
        ("g0_nasa_apollo15_moon",),
    ),
    (
        "q018",
        "When did Apollo 15 lift off?",
        ("paraphrase",),
        False,
        "answer",
        ("July 26, 1971",),
        (),
        "TEMPORAL_WHEN",
        "apollo_15",
        "launched_on",
        ("g0_nasa_apollo15_launch",),
    ),
    (
        "q019",
        "Where did Apollo 16 land?",
        ("fact",),
        False,
        "answer",
        ("Descartes",),
        (),
        "FACT_LOOKUP",
        "apollo_16",
        "landed_at",
        ("g0_nasa_apollo16_moon",),
    ),
    (
        "q020",
        "When was Apollo 16 launched?",
        ("fact",),
        False,
        "answer",
        ("April 16, 1972",),
        (),
        "TEMPORAL_WHEN",
        "apollo_16",
        "launched_on",
        ("g0_nasa_apollo16_launch",),
    ),
    (
        "q021",
        "Which Apollo mission was the final lunar landing mission?",
        ("paraphrase",),
        False,
        "answer",
        ("Apollo 17",),
        (),
        "FACT_LOOKUP",
        "apollo_program",
        "final_lunar_mission",
        ("g0_nasa_apollo17_launch",),
    ),
    (
        "q022",
        "What date did Apollo 17 launch?",
        ("fact",),
        False,
        "answer",
        ("December 7, 1972",),
        (),
        "TEMPORAL_WHEN",
        "apollo_17",
        "launched_on",
        ("g0_nasa_apollo17_launch",),
    ),
    (
        "q023",
        "What happened to the Apollo 1 crew?",
        ("fact",),
        True,
        "answer",
        ("fire",),
        (),
        "FACT_LOOKUP",
        "apollo_1",
        "crew_event",
        ("g0_nasa_apollo1_fire",),
    ),
    (
        "q024",
        "Was the Apollo 1 accident in flight?",
        ("negation",),
        True,
        "answer",
        ("ground",),
        ("in flight",),
        "FACT_LOOKUP",
        "apollo_1",
        "accident_context",
        ("g0_nasa_apollo1_fire",),
    ),
    (
        "q025",
        "What vehicle did Armstrong eject from during training?",
        ("fact",),
        False,
        "answer",
        ("Lunar Landing Research Vehicle",),
        (),
        "FACT_LOOKUP",
        "neil_armstrong",
        "ejected_from",
        ("g0_nasa_armstrong_llrv",),
    ),
    (
        "q026",
        "How was the Apollo 11 crew recovered after splashdown?",
        ("fact",),
        False,
        "answer",
        ("helicopter",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "recovered_by",
        ("g0_nasa_apollo11_recovery",),
    ),
    (
        "q027",
        "What science instruments did Apollo 11 leave on the Moon?",
        ("missing_evidence",),
        True,
        "abstain",
        ("evidence",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "left_instruments",
        (),
    ),
    (
        "q028",
        "How many pounds of lunar samples did Apollo 11 collect?",
        ("quantity",),
        True,
        "answer",
        ("47.5",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "sample_mass",
        ("g0_nasa_apollo11_science",),
    ),
    (
        "q029",
        "Which nation first landed humans on the Moon?",
        ("fact",),
        False,
        "answer",
        ("United States",),
        (),
        "FACT_LOOKUP",
        "united_states",
        "first_human_lunar_landing",
        ("g0_nasa_human_spaceflight_record",),
    ),
    (
        "q030",
        "How many people walked on the Moon during Apollo?",
        ("quantity",),
        False,
        "answer",
        ("12",),
        (),
        "FACT_LOOKUP",
        "apollo_program",
        "moonwalker_count",
        ("g0_nasa_apollo_program",),
    ),
    (
        "q031",
        "Did Michael Collins walk on the lunar surface?",
        ("incorrect_premise", "negation"),
        True,
        "answer",
        ("lunar orbit",),
        ("walked on the Moon",),
        "FACT_LOOKUP",
        "michael_collins",
        "role",
        ("g0_nasa_apollo11_mission_overview",),
    ),
    (
        "q032",
        "Was Eagle the Apollo 13 lunar module?",
        ("entity_substitution", "incorrect_premise"),
        True,
        "abstain",
        ("Apollo 13",),
        ("Apollo 11 used Eagle",),
        "FACT_LOOKUP",
        "apollo_13",
        "used_vehicle",
        (),
    ),
    (
        "q033",
        "When did Apollo 18 land on the Moon?",
        ("entity_substitution", "unknown_span"),
        True,
        "abstain",
        ("Apollo 18",),
        (),
        "TEMPORAL_WHEN",
        "apollo_18",
        "landed_on",
        (),
    ),
    (
        "q034",
        "Did Apollo 12 visit Surveyor II?",
        ("entity_substitution", "incorrect_premise"),
        True,
        "abstain",
        ("Surveyor II",),
        ("Surveyor III",),
        "FACT_LOOKUP",
        "apollo_12",
        "visited",
        (),
    ),
    (
        "q035",
        "Was Apollo 15 launched in 1972?",
        ("incorrect_premise", "temporal"),
        True,
        "answer",
        ("1971",),
        ("1972",),
        "FACT_LOOKUP",
        "apollo_15",
        "launched_on",
        ("g0_nasa_apollo15_launch",),
    ),
    (
        "q036",
        "Did Apollo 16 land at Fra Mauro?",
        ("entity_substitution", "incorrect_premise"),
        True,
        "answer",
        ("Descartes",),
        ("Fra Mauro",),
        "FACT_LOOKUP",
        "apollo_16",
        "landed_at",
        ("g0_nasa_apollo16_moon",),
    ),
    (
        "q037",
        "Who commanded Apollo 19?",
        ("entity_substitution", "unknown_span"),
        True,
        "abstain",
        ("Apollo 19",),
        (),
        "FACT_LOOKUP",
        "apollo_19",
        "had_commander",
        (),
    ),
    (
        "q038",
        "Did Apollo 11 use an RV1106 processor?",
        ("unknown_span",),
        True,
        "abstain",
        ("RV1106",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "used_processor",
        (),
    ),
    (
        "q039",
        "What did the Zephyr valve do on Apollo 14?",
        ("unknown_span",),
        True,
        "abstain",
        ("Zephyr",),
        (),
        "FACT_LOOKUP",
        "zephyr_valve",
        "purpose",
        (),
    ),
    (
        "q040",
        "Where is Tranquility Engine 9 documented?",
        ("unknown_span",),
        True,
        "abstain",
        ("Tranquility Engine 9",),
        (),
        "FACT_LOOKUP",
        "tranquility_engine_9",
        "documented_at",
        (),
    ),
    (
        "q041",
        "Who won the 1972 World Series?",
        ("out_of_domain",),
        True,
        "out_of_domain",
        ("Outside",),
        (),
        "UNKNOWN",
        None,
        None,
        (),
    ),
    (
        "q042",
        "What is the capital of Mongolia?",
        ("out_of_domain",),
        True,
        "out_of_domain",
        ("Outside",),
        (),
        "UNKNOWN",
        None,
        None,
        (),
    ),
    (
        "q043",
        "How do I bake sourdough bread?",
        ("out_of_domain",),
        True,
        "out_of_domain",
        ("Outside",),
        (),
        "UNKNOWN",
        None,
        None,
        (),
    ),
    (
        "q044",
        "What was yesterday's weather in Denver?",
        ("out_of_domain",),
        True,
        "out_of_domain",
        ("Outside",),
        (),
        "UNKNOWN",
        None,
        None,
        (),
    ),
    (
        "q045",
        "Which stock gained the most today?",
        ("out_of_domain",),
        True,
        "out_of_domain",
        ("Outside",),
        (),
        "UNKNOWN",
        None,
        None,
        (),
    ),
    (
        "q046",
        "What fuel ratio did the Apollo 11 engine use?",
        ("missing_evidence",),
        True,
        "abstain",
        ("ontology",),
        (),
        "FACT_LOOKUP",
        "apollo_11",
        "fuel_ratio",
        (),
    ),
    (
        "q047",
        "What was Apollo 14's exact cabin pressure at landing?",
        ("missing_evidence", "quantity"),
        True,
        "abstain",
        ("evidence",),
        (),
        "FACT_LOOKUP",
        "apollo_14",
        "cabin_pressure",
        (),
    ),
    (
        "q048",
        "Two NASA pages repeat Apollo 11's landing date; when was it?",
        ("duplicated_source_evidence",),
        True,
        "answer",
        ("July 20, 1969",),
        (),
        "TEMPORAL_WHEN",
        "apollo_11",
        "landed_on",
        ("g0_nasa_apollo11_mission_overview", "g0_nasa_apollo11_mission_card"),
    ),
    (
        "q049",
        "If two source revisions disagree on Apollo 11's return date, which date is supported?",
        ("conflicting_source",),
        True,
        "abstain",
        ("conflicting",),
        (),
        "TEMPORAL_WHEN",
        "apollo_11",
        "returned_on",
        ("g0_nasa_apollo11_recovery",),
    ),
    (
        "q050",
        "Resolve the conflicting reported launch dates for Apollo 16.",
        ("conflicting_source", "temporal"),
        True,
        "abstain",
        ("conflicting",),
        (),
        "TEMPORAL_WHEN",
        "apollo_16",
        "launched_on",
        ("g0_nasa_apollo16_launch",),
    ),
)


def build_pending_query_set(output_path: Path) -> SealedQuerySet:
    cases = []
    for spec in QUERY_SPECS:
        (
            case_id,
            question,
            categories,
            hard_subset,
            expected_disposition,
            expected_contains,
            forbidden_contains,
            intent,
            entity_id,
            relation_id,
            evidence_source_ids,
        ) = spec
        cases.append(
            SealedQueryCase(
                case_id=case_id,
                question=question,
                categories=categories,
                hard_subset=hard_subset,
                expected_disposition=Disposition(expected_disposition),
                expected_contains=expected_contains,
                forbidden_contains=forbidden_contains,
                reviewed_frame={
                    "intent": intent,
                    "entity_id": entity_id,
                    "relation_id": relation_id,
                },
                evidence_source_ids=evidence_source_ids,
                evidence_candidate_ids=(),
                author_identity=AUTHOR_IDENTITY,
                authoring_process=AUTHORING_PROCESS,
                review_status=QueryReviewStatus.PENDING_HUMAN_REVIEW,
            )
        )
    query_set = SealedQuerySet(
        query_set_id="apollo_gate0_sealed_candidates_v1",
        schema_version="1.0.0",
        independence_statement=(
            "These cases were authored separately from the deterministic rule "
            "extractor. They are candidates, not a reviewed or opened sealed test."
        ),
        cases=tuple(cases),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(query_set.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return query_set
