#!/usr/bin/env python3
"""Bind the selected V14 int8 policy artifact into a C include for the P4 build.

Reads reports/droid/v14/controller-selected-policy-int8.json and emits
main/policy_v14_selected.h with the row-major int8 weight array. The artifact
carries its bias as feature row 0 (feature_scale=256 constant), so the native
ABI bias pointer remains NULL; no parameters are added or dropped here.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ARTIFACT = ROOT / "reports/droid/v14/controller-selected-policy-int8.json"
OUTPUT = Path(__file__).resolve().parents[1] / "main/policy_v14_selected.h"


def main() -> None:
    payload = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    if payload["schema_version"] != "aethercore.cog-masked-linear-policy.int8.v1":
        raise SystemExit(f"unexpected policy schema: {payload['schema_version']}")
    weights = payload["weights_int8"]
    feature_count = len(payload["feature_names"])
    action_count = len(payload["operation_ids"])
    flat = [item for row in weights for item in row]
    if len(weights) != action_count or any(len(row) != feature_count for row in weights):
        raise SystemExit("policy weight shape mismatch")
    if any(not -128 <= item <= 127 for item in flat):
        raise SystemExit("policy weight outside int8")
    digest = hashlib.sha256(ARTIFACT.read_bytes()).hexdigest()
    lines = [
        "/* Generated by tools/embed_policy.py from the frozen V14 artifact.",
        f" * artifact sha256: {digest}",
        " * Do not edit by hand. */",
        "#pragma once",
        "#include <stdint.h>",
        f"#define AC_V14_POLICY_FEATURE_COUNT {feature_count}u",
        f"#define AC_V14_POLICY_ACTION_COUNT {action_count}u",
        f"#define AC_V14_POLICY_PARAMETER_COUNT {len(flat)}u",
        "#define AC_V14_POLICY_STATE_SCHEMA_ID 1u",
        "#define AC_V14_POLICY_MODEL_ID 14u",
        "static const int8_t kAcV14PolicyWeights[AC_V14_POLICY_PARAMETER_COUNT] = {",
    ]
    for index in range(0, len(flat), 16):
        lines.append("  " + ", ".join(str(item) for item in flat[index : index + 16]) + ",")
    lines.append("};")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(flat)} int8 parameters, artifact {digest[:16]}…)")


if __name__ == "__main__":
    main()
